name: Merkle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  suma_modular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install -g snarkjs
    - name: Run suma_modular cases
      run: |
        # Usamos directamente lo subido al repo
        node run_cases.js

  merkle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install -g snarkjs
    - name: Run merkle cases
      run: |
        # Usamos directamente lo subido al repo
        node run_casesMerkle.js

  merkleN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm install -g snarkjs
    - name: Run merkleN cases
      run: |
        # Usamos directamente lo subido al repo
        node run_casesMerkleN.js



